# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408e5bc06667c0d32647bb551aa646fda92ec6244092f395895dde253e6027fdb219076a2937c4ca9f0fcd04919fe751d4d42e013c0a46308f159657561709aa

test:
  secret_key_base: 1f8550c9b4803ad8c62e48ac150466dce513a5a3c778b41a777b6ec8641d26e93a6cfbd652e43355de086f2feaab0d7a40a435835a1c1202f571bef959809341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
